run:
	cargo run
watch:
	cargo watch -X check
check:
	cargo check
test:
	cargo test
coverage:
	cargo tarpaulin --ignore-tests
lint:
	cargo clippy -- -D warnings
format:
	cargo fmt
audit:
	cargo audit
db-run:
	SKIP_DOCKER=true ./scripts/init_db.sh
db-cli:
	psql -d postgres -U postgres -h 127.0.0.1 -p 5432