run:
	cargo run
watch:
	cargo watch -x run
watch-check:
	cargo watch -x check
check:
	cargo check
test:
	TEST_LOG=true cargo test | bunyan
coverage:
	cargo tarpaulin --ignore-tests
lint:
	cargo clippy -- -D warnings
format:
	cargo fmt
audit:
	cargo audit
unused-dep:
	cargo +nightly udeps
script-db:
	SKIP_DOCKER=true ./scripts/init_db.sh
script-redis:
	./scripts/init_redis.sh
db-cli:
	psql -d postgres -U postgres -h 127.0.0.1 -p 5432
db-add:
	sqlx migrate add $(name)
db-migrate:
	sqlx migrate run
docker-build:
	docker build --tag monkey_letter --file Dockerfile .
docker-run:
	docker run -p 8000:8000 monkey_letter