application:
  port: 8000
  hmac_secret: "something-very-secret-here-also-typing-more-to-make-it-longer-thisissupersecret"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "monkey_letter"
email_client:
  base_url: "localhost"
  sender_email: "test@test.com"
  authorization_token: "test-secret-token"
  timeout_milliseconds: 10000
redis_url: "redis://127.0.0.1:6379"
