name: Rust

on: [push, pull_request]

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@stable
            - uses: Swatinem/rust-cache@v2
            - name: Run Tests
              run: cargo test

    fmt:
        name: Rust Format
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@stable
              with:
                components: rustfmt
            - name: Enforce formatting
              run: cargo fmt --check

    clippy:
        name: Clippy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@stable
              with:
                component: clippy
            - uses: Swatinem/rust-cache@v2
            - name: Linting
              run: cargo clippy -- -D warning

    coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        container:
            image: xd009642/tarpaulin
            options: --security-opt seccomp=unconfined
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Generate Code Coverage
              run: |
                cargo tarpaulin --verbose --workspace
              